### ISSUE TITLE
Auction start time is wrong

### ISSUE THREAD

**Issue by xiaohanzhu** [meterio/meter-wallet#6]
**Describe the bug**
The auction start time inside the wallet is displayed as 1/19 XXXX
![wallet](https://user-images.githubusercontent.com/9540395/83990010-12926e00-a8fd-11ea-8498-aae3955e6b13.png)

**Comment by simonzg** [comment]
solved by commit [7e7546](https://github.com/meterio/meter-wallet/commit/7e75464ce506ccaae27d5b451d03587d7fa4538e)
